# Generated by Django 3.1.9 on 2021-05-05 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('batch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lote')),
                ('qty_records', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identificador da Linha')),
                ('batch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Númeração do Lote')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de Cartão Completo')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.card', verbose_name='Cartão')),
            ],
            options={
                'verbose_name': 'Linha do Cartão',
                'verbose_name_plural': 'Linhas do Cartão',
                'ordering': ['-created_at'],
            },
        ),
    ]
