# Generated by Django 3.1.9 on 2021-05-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210505_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='qty_records',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qtd Registros'),
        ),
    ]
